### ISSUE TITLE
README.md 적용 이미지 누락

### ISSUE THREAD

**Issue by dabrewdanya** [BoothPlus/BoothPlus#3]
README.md에 적용 이미지가 누락되어 있습니다.

https://github.com/vrc-booth/vrc-booth-extension/blob/bd7bb1202881a8ebdd5faf944a01c9a6d764bafe/README.md?plain=1#L17

**Comment by ribeKim** [comment]
Docs: 프로젝트 관련 문서 추가 #4
PR에 머지하였습니다.

이슈 종결하겠습니다!
